version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: farm_api:${FARM_API_VERSION:-latest}
    restart: always
    env_file:
    - .env
    depends_on:
      redis:
        condition: service_healthy
    environment:
      FARM_API_HOST: 0.0.0.0
      FARM_API_REDIS_HOST: farm_api-redis

  redis:
    image: bitnami/redis:6.2.5
    hostname: "farm_api-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50
